[build]
  command = "cd aimee-web && npm install && npm run build"
  publish = "aimee-web/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"





# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"



# Fix CSS MIME types
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"

# Fix JS MIME types
[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Content-Type = "application/javascript"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js handles its own routing via the plugin

[dev]
  functions = "netlify/functions"
  port = 3000 