[build]
  command = "cd aimee-web && npm install && npm run build"
  publish = "aimee-web/out"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"





# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"



# Fix CSS MIME types
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"

# Fix JS MIME types
[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Content-Type = "application/javascript"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle client-side routing for static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  functions = "netlify/functions"
  port = 3000 